import type { Tool, Category, SiteConfig, NavItem } from "@/types";

export const siteConfig: SiteConfig = {
  name: "DevStackIO",
  description:
    "The internet's best collection of free online tools for developers. JSON formatters, JWT decoders, image compressors, and more.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://tools.devstackio.com",
  ogImage: "/og.svg",
  links: {
    github: "https://github.com/roddavinod99",
  },
  contactEmail: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "contact@devstackio.com",
  legal: {
    lastUpdated: {
      privacy: "2026-06-15",
      terms: "2026-06-15",
      cookie: "2026-06-15",
      disclaimer: "2026-06-15",
    },
  },
};

export const mainNav: NavItem[] = [
  { title: "Tools", href: "/tools" },
  { title: "Categories", href: "/categories" },
  { title: "Guides", href: "/guides" },
  { title: "Blog", href: "/blog" },
  { title: "Learning", href: "/learning" },
  { title: "API", href: "/api" },
];

const categoryMetas: Array<Omit<Category, 'toolCount'>> = [
  { id: "1", name: "Encoders", description: "Text and data encoding tools for converting between formats", slug: "encoders", icon: "FileCode", seoKeywords: ["encoder", "decoder", "base64", "url encoding", "html entities", "binary", "hex", "escape unescape"], seoFeatures: ["Encode and decode various formats", "Support multiple encoding schemes", "Browser-based processing for privacy", "Real-time conversion", "No data transmitted to servers", "Free and unlimited use"] },
  { id: "2", name: "Formatters", description: "Code and data formatting, beautification, and validation tools", slug: "formatters", icon: "PanelRightOpen", seoKeywords: ["formatter", "validator", "json", "code formatter", "beautifier", "minifier", "syntax validation"], seoFeatures: ["Format and validate code", "Real-time syntax checking", "Multiple format support", "Beautify and minify options", "Syntax highlighting", "Error detection and reporting"] },
  { id: "3", name: "Generators", description: "Generate IDs, passwords, QR codes, random data, and more", slug: "generators", icon: "Wand", seoKeywords: ["generator", "uuid", "password", "qr code", "random data", "barcode", "ascii art", "lorem ipsum"], seoFeatures: ["Generate unique identifiers", "Create secure passwords", "Bulk generation support", "Multiple format options", "Instant generation", "Copy to clipboard"] },
  { id: "4", name: "Converters", description: "Convert between data formats, units, colors, and timestamps", slug: "converters", icon: "ArrowLeftRight", seoKeywords: ["converter", "json to csv", "csv to json", "markdown", "timestamp", "unit converter", "color converter", "base converter"], seoFeatures: ["Convert between multiple formats", "Instant conversion results", "Support various unit systems", "Real-time conversion", "No registration required", "Free and unlimited use"] },
  { id: "5", name: "Security Tools", description: "Security, cryptography, and authentication tools", slug: "security", icon: "Shield", seoKeywords: ["security", "jwt", "hash", "totp", "ssl", "csp", "checksum", "cryptography"], seoFeatures: ["Generate cryptographic hashes", "Decode and analyze JWT tokens", "Multiple hash algorithms", "Browser-based security", "No data transmission", "Instant hash generation"] },
  { id: "6", name: "Image Tools", description: "Image processing, optimization, and conversion tools", slug: "image-tools", icon: "Image", seoKeywords: ["image", "resizer", "compressor", "favicon", "svg", "exif", "placeholder", "base64 image"], seoFeatures: ["Resize images to any dimensions", "Compress images for web", "Convert between image formats", "Browser-based processing for privacy", "No uploads required", "Free and unlimited use"] },
  { id: "7", name: "Utilities", description: "Text analysis, development, and utility tools", slug: "utilities", icon: "Wrench", seoKeywords: ["utilities", "regex", "diff", "word counter", "text analysis", "cron", "url parser", "user agent", "dns", "ip", "network"], seoFeatures: ["Analyze and compare text", "Test regular expressions", "Count words and characters", "Real-time analysis", "Browser-based processing", "Free to use"] },
];

export const allTools: Tool[] = [
  // ── Encoders (10) ──
  { id: "e1", name: "Base64 Encoder/Decoder", description: "Free online Base64 encoder and decoder tool for developers. Instantly convert text and files to Base64 format and decode Base64 strings back to readable text.", category: "Encoders", slug: "base64", popularity: 95, icon: "FileCode", featured: true, trending: true },
  { id: "e2", name: "URL Encoder/Decoder", description: "Free URL encoder and decoder tool for web developers. Encode special characters in URLs and query parameters or decode percent-encoded strings instantly.", category: "Encoders", slug: "url-encoder", popularity: 90, icon: "Link", featured: true },
  { id: "e3", name: "HTML Entity Encoder/Decoder", description: "Free online HTML entity encoder and decoder. Convert special characters like angle brackets and ampersands to HTML entities and back for safe web dev.", category: "Encoders", slug: "html-entity", popularity: 70, icon: "Code" },
  { id: "e4", name: "Binary Encoder/Decoder", description: "Free binary encoder and decoder for developers. Convert any text string to binary representation and decode binary back to readable text instantly online.", category: "Encoders", slug: "binary", popularity: 65, icon: "Binary" },
  { id: "e5", name: "Hex Encoder/Decoder", description: "Free hexadecimal encoder and decoder tool. Convert text to hex format and decode hexadecimal strings back to readable text with this easy online utility.", category: "Encoders", slug: "hex", popularity: 68, icon: "Hash" },
  { id: "e6", name: "String Escape/Unescape", description: "Free string escape and unescape tool for developers. Handle escape sequences for JavaScript, JSON, HTML, URL, and more with instant real-time conversion.", category: "Encoders", slug: "escape-unescape", popularity: 72, icon: "Quote" },
  { id: "e7", name: "Base64 Image Converter", description: "Convert images to Base64 encoded strings online for free. Generate Base64 data URIs for embedding images directly in HTML, CSS, and JavaScript code.", category: "Encoders", slug: "image-to-base64", popularity: 74, icon: "Image" },
  { id: "e8", name: "Morse Code Converter", description: "Free online Morse code converter with audio playback. Translate text to Morse code and decode Morse code back to text with sound for easy learning.", category: "Encoders", slug: "morse-code", popularity: 55, icon: "Circle" },
  { id: "e9", name: "Base64 Decoder", description: "Free Base64 decoder with automatic encoding detection and file download support. Paste or upload Base64 data to decode it back to text or binary files.", category: "Encoders", slug: "base64-decoder", popularity: 60, icon: "FileCode" },
  { id: "e10", name: "Base64 Encoder", description: "Free Base64 encoder tool with multiple encoding presets for developers. Encode plain text and file uploads to Base64 format with customizable options.", category: "Encoders", slug: "base64-encoder", popularity: 60, icon: "FileCode" },

  // ── Formatters (17) ──
  { id: "f1", name: "JSON Formatter", description: "Free online JSON formatter and validator with syntax highlighting. Beautify, validate, and minify JSON data instantly with real-time error detection.", category: "Formatters", slug: "json-formatter", popularity: 98, icon: "Braces", featured: true, trending: true, worker: true, aliasSlugs: ["json-pretty", "json-lint", "json-viewer"], keywords: ["json", "formatter", "beautifier", "minifier", "validator", "pretty print", "lint"] },
  { id: "f2", name: "HTML Formatter/Validator", description: "Free HTML formatter and validator tool for web developers. Beautify, minify, and validate HTML code online with syntax error detection and reporting.", category: "Formatters", slug: "html-formatter", popularity: 82, icon: "Code" },
  { id: "f3", name: "CSS Formatter/Minifier", description: "Free CSS formatter, beautifier, and minifier tool online. Format, prettify, and compress CSS code with syntax highlighting and customizable indentation.", category: "Formatters", slug: "css-formatter", popularity: 78, icon: "Palette" },
  { id: "f4", name: "JavaScript Minifier/Beautifier", description: "Free JavaScript minifier and beautifier with customizable options. Minify JS code for production or beautify it for readability with syntax validation.", category: "Formatters", slug: "js-minifier", popularity: 85, icon: "FileCode", featured: true },
  { id: "f5", name: "SQL Formatter", description: "Free online SQL formatter and beautifier with syntax validation. Format and prettify complex SQL queries for MySQL, PostgreSQL, and SQLite databases.", category: "Formatters", slug: "sql-formatter", popularity: 92, icon: "Database", featured: true },
  { id: "f6", name: "XML Formatter/Validator", description: "Free XML formatter, validator, and minifier tool online. Beautify, compress, and validate XML documents with real-time syntax error detection.", category: "Formatters", slug: "xml-formatter", popularity: 72, icon: "FileX" },
  { id: "f7", name: "YAML Formatter/Validator", description: "Free online YAML formatter and validator for developers. Format, validate, and minify YAML files and configuration with syntax error detection.", category: "Formatters", slug: "yaml-formatter", popularity: 70, icon: "FileType" },
  { id: "f8", name: "Text Analyzer", description: "Free online text analyzer tool with character, word, and sentence counting. Analyze text readability with Flesch scores and language statistics.", category: "Formatters", slug: "text-analyzer", popularity: 76, icon: "Hash" },
  { id: "f9", name: "JSON Diff Checker", description: "Free JSON diff checker tool for developers. Compare two JSON objects side-by-side and highlight differences with detailed structural comparison.", category: "Formatters", slug: "json-diff", popularity: 75, icon: "GitCompare", featured: true },
  { id: "f10", name: "JSON Beautifier", description: "Free online JSON beautifier with configurable indentation and color themes. Format and style JSON data for improved readability and presentation.", category: "Formatters", slug: "json-beautifier", popularity: 74, icon: "Braces", featured: true },
  { id: "f11", name: "JSON Minifier", description: "Free online JSON minifier tool for developers. Remove unnecessary whitespace and formatting from JSON data to reduce payload size for APIs.", category: "Formatters", slug: "json-minifier", popularity: 70, icon: "Braces" },
  { id: "f12", name: "JSON Validator", description: "Free JSON validator tool with detailed error messages and line-level reporting. Validate JSON syntax instantly and find errors in your data.", category: "Formatters", slug: "json-validator", popularity: 73, icon: "Braces" },
  { id: "f13", name: "CSS Minifier", description: "Free online CSS minifier tool for web performance. Remove whitespace and comments from CSS code to reduce file size and speed up page loads.", category: "Formatters", slug: "css-minifier", popularity: 60, icon: "Palette" },
  { id: "f14", name: "HTML Minifier", description: "Free online HTML minifier for optimized web output. Remove unnecessary whitespace, comments, and redundant code from HTML for faster loading.", category: "Formatters", slug: "html-minifier", popularity: 62, icon: "Code" },
  { id: "f15", name: "Docker Run to Compose", description: "Convert docker run commands to Docker Compose YAML files online for free. Simplify container orchestration with this easy migration tool.", category: "Formatters", slug: "docker-run-to-compose", popularity: 65, icon: "FileCode" },
  { id: "f16", name: "YAML Viewer", description: "Free online YAML viewer and pretty-printer with syntax highlighting. View, format, and validate YAML configuration files in your browser.", category: "Formatters", slug: "yaml-viewer", popularity: 62, icon: "FileType" },
  { id: "f17", name: "Benchmark Builder", description: "Free online JavaScript benchmark builder for measuring code execution time. Test and compare performance of different code snippets accurately.", category: "Formatters", slug: "benchmark-builder", popularity: 58, icon: "Zap" },

  // ── Generators (15) ──
  { id: "g1", name: "UUID Generator", description: "Free online UUID generator tool for developers. Generate UUID v4 and v7 universally unique identifiers instantly with one-click copy to clipboard.", category: "Generators", slug: "uuid-generator", popularity: 90, icon: "FingerprintPattern", featured: true, aliasSlugs: ["guid-generator", "unique-id", "uuid-gen"] },
  { id: "g2", name: "Password Generator", description: "Free secure password generator with customizable length, characters, and complexity options. Create strong random passwords for accounts and apps.", category: "Generators", slug: "password-generator", popularity: 85, icon: "Lock", featured: true, aliasSlugs: ["random-password", "strong-password", "password-gen"] },
  { id: "g3", name: "QR Code Generator", description: "Free online QR code generator with customizable colors, logos, and styling options. Create high-quality QR codes for URLs, text, and contact info.", category: "Generators", slug: "qr-generator", popularity: 88, icon: "QrCode", featured: true, trending: true, keywords: ["qr", "qr code", "qrcode", "scan", "barcode"] },
  { id: "g4", name: "Random Data Generator", description: "Free random data generator for software testing and development. Generate realistic fake names, emails, addresses, and other test data instantly.", category: "Generators", slug: "random-data", popularity: 74, icon: "Shuffle" },
  { id: "g5", name: "ASCII Art Generator", description: "Free online ASCII art text generator with various fonts and styles. Convert text to decorative ASCII art for terminals, comments, and documents.", category: "Generators", slug: "ascii-art", popularity: 62, icon: "TextCursor" },
  { id: "g6", name: "Barcode Generator", description: "Free online barcode generator supporting Code128, EAN, UPC, and more formats. Create scannable barcodes for products, inventory, and labels.", category: "Generators", slug: "barcode-generator", popularity: 66, icon: "Barcode" },
  { id: "g7", name: "Lorem Ipsum Generator", description: "Free Lorem Ipsum placeholder text generator with multiple styles. Generate dummy text paragraphs for web design, mockups, and content layouts.", category: "Generators", slug: "lorem-ipsum", popularity: 70, icon: "Type" },
  { id: "g8", name: "Cron Expression Generator", description: "Free cron expression generator with visual editor and timezone support. Build and validate cron schedules for job automation and task scheduling.", category: "Generators", slug: "cron-expression", popularity: 60, icon: "Clock" },
  { id: "g9", name: "AI Prompt Generator", description: "Free AI prompt generator with customizable templates and variables. Create effective prompts for ChatGPT, Claude, and other AI tools easily.", category: "Generators", slug: "prompt-generator", popularity: 58, icon: "Wand" },
  { id: "g10", name: "AI Prompt Improver", description: "Free AI prompt enhancer and optimizer tool. Refine and improve your prompts with structured revision templates for better AI-generated results.", category: "Generators", slug: "prompt-improver", popularity: 56, icon: "Wand" },
  { id: "g11", name: "Random Port Generator", description: "Free random port number generator for software development. Generate available port numbers for local servers, databases, and applications.", category: "Generators", slug: "random-port-generator", popularity: 58, icon: "Shuffle" },
  { id: "g12", name: "Meta Tag Generator", description: "Free HTML meta tag generator for SEO and social media sharing. Create Open Graph, Twitter Card, and description meta tags for your website.", category: "Generators", slug: "meta-tag-generator", popularity: 68, icon: "Code" },
  { id: "g13", name: "Token Generator", description: "Free random API token and secret generator with configurable character sets and entropy. Create secure tokens for authentication and encryption.", category: "Generators", slug: "token-generator", popularity: 62, icon: "Key" },
  { id: "g14", name: "WiFi QR Code Generator", description: "Free WiFi QR code generator for easy network sharing. Create QR codes that connect guests to your WiFi network automatically when scanned.", category: "Generators", slug: "wifi-qr-generator", popularity: 66, icon: "QrCode" },
  { id: "g15", name: "Numeronym Generator", description: "Free numeronym generator tool for developers. Create shorthand abbreviations like k8s, i18n, and a11y from words and phrases instantly.", category: "Generators", slug: "numeronym-generator", popularity: 52, icon: "Hash" },

  // ── Converters (22) ──
  { id: "c1", name: "JSON to CSV Converter", description: "Free online JSON to CSV converter with advanced formatting options. Transform JSON arrays into spreadsheet-ready CSV files with customizable delimiters.", category: "Converters", slug: "json-to-csv", popularity: 84, icon: "Table", featured: true, worker: true, keywords: ["json", "csv", "converter", "export", "spreadsheet"] },
  { id: "c2", name: "CSV to JSON Converter", description: "Free CSV to JSON converter tool for developers. Parse and convert CSV data to structured JSON format with advanced parsing and formatting options.", category: "Converters", slug: "csv-to-json", popularity: 82, icon: "FileSpreadsheet", worker: true, keywords: ["csv", "json", "converter", "parser", "spreadsheet"] },
  { id: "c3", name: "JSON to XML Converter", description: "Free online JSON to XML converter with customizable options. Transform JSON data into well-formatted XML documents for data interchange.", category: "Converters", slug: "json-to-xml", popularity: 68, icon: "FileX" },
  { id: "c4", name: "XML to JSON Converter", description: "Free online XML to JSON converter with customizable options. Parse and convert XML documents into structured JSON data for modern applications.", category: "Converters", slug: "xml-to-json", popularity: 70, icon: "FileCode" },
  { id: "c5", name: "Markdown to HTML Converter", description: "Free Markdown to HTML converter with live preview and GitHub Flavored Markdown support. Transform Markdown documents into formatted HTML instantly.", category: "Converters", slug: "markdown-to-html", popularity: 78, icon: "FileText" },
  { id: "c6", name: "HTML to Markdown Converter", description: "Free HTML to Markdown converter tool for developers. Convert HTML code and web pages into clean, readable Markdown format with customizable options.", category: "Converters", slug: "html-to-markdown", popularity: 72, icon: "FileDown" },
  { id: "c7", name: "JSON to YAML Converter", description: "Free online JSON to YAML converter tool. Transform JSON data into clean, readable YAML format and vice versa with instant real-time conversion.", category: "Converters", slug: "json-to-yaml", popularity: 74, icon: "FileType" },
  { id: "c8", name: "TOML/JSON/YAML Converter", description: "Free TOML, JSON, and YAML converter tool for developers. Convert configuration files between these popular data serialization formats easily.", category: "Converters", slug: "toml-converter", popularity: 58, icon: "Repeat" },
  { id: "c9", name: "Timestamp Converter", description: "Free Unix timestamp converter for developers. Convert Unix timestamps to human-readable dates and back with timezone support and multiple formats.", category: "Converters", slug: "timestamp-converter", popularity: 79, icon: "Clock", featured: true },
  { id: "c10", name: "Color Converter", description: "Free online color converter for designers and developers. Convert between HEX, RGB, HSL, HSV, and CMYK color formats with palette generation.", category: "Converters", slug: "color-converter", popularity: 76, icon: "Palette" },
  { id: "c11", name: "Unit Converter", description: "Free online unit converter for measurement conversions. Convert between metric, imperial, and other unit systems for length, weight, and more.", category: "Converters", slug: "unit-converter", popularity: 72, icon: "Ruler" },
  { id: "c12", name: "Case Converter", description: "Free online text case converter for developers. Convert strings between camelCase, snake_case, kebab-case, PascalCase, and other naming conventions.", category: "Converters", slug: "case-converter", popularity: 68, icon: "CaseSensitive" },
  { id: "c13", name: "Base Converter", description: "Free online number base converter for developers. Convert numbers between binary, octal, decimal, hexadecimal, and base36 number systems instantly.", category: "Converters", slug: "base-converter", popularity: 64, icon: "Binary" },
  { id: "c14", name: "Number to Words", description: "Free online number to words converter in English. Transform any numeric value into its written word representation for documents and checks.", category: "Converters", slug: "number-to-words", popularity: 56, icon: "Heading" },
  { id: "c15", name: "JSON to TypeScript", description: "Free JSON to TypeScript converter tool. Automatically generate TypeScript interfaces, types, and type definitions from sample JSON data.", category: "Converters", slug: "json-to-typescript", popularity: 80, icon: "FileCode", featured: true, new: true },
  { id: "c16", name: "JSON to Go Struct", description: "Free JSON to Go struct converter for developers. Generate Go struct definitions with proper types and tags from JSON data automatically.", category: "Converters", slug: "json-to-go", popularity: 66, icon: "FileCode" },
  { id: "c17", name: "Markdown Editor", description: "Free online Markdown editor with live preview and syntax highlighting. Write and preview Markdown with GitHub Flavored Markdown support built in.", category: "Converters", slug: "markdown-editor", popularity: 65, icon: "FileText" },
  { id: "c18", name: "Roman Numeral Converter", description: "Free online Roman numeral converter for quick translations. Convert between Roman numerals and integer values with instant real-time results.", category: "Converters", slug: "roman-numeral-converter", popularity: 60, icon: "Hash" },
  { id: "c19", name: "Text to NATO Alphabet", description: "Free text to NATO phonetic alphabet converter online. Convert text to military phonetic alphabet for clear radio and voice communication.", category: "Converters", slug: "nato-alphabet", popularity: 55, icon: "Globe" },
  { id: "c20", name: "Text to Unicode", description: "Free online text to Unicode code point converter for developers. Transform text characters into Unicode code points and decode them back easily.", category: "Converters", slug: "text-to-unicode", popularity: 58, icon: "Code" },
  { id: "c21", name: "List Converter", description: "Free online list format converter for developers and data analysts. Convert between CSV, JSON, one-per-line, and other popular list formats instantly.", category: "Converters", slug: "list-converter", popularity: 62, icon: "FileSpreadsheet" },
  { id: "c22", name: "Temperature Converter", description: "Free online temperature converter for quick unit conversions. Convert between Celsius, Fahrenheit, and Kelvin with instant real-time results.", category: "Converters", slug: "temperature-converter", popularity: 65, icon: "Ruler" },

  // ── Security Tools (8) ──
  { id: "s1", name: "JWT Decoder", description: "Free online JWT decoder and analyzer for developers. Inspect JSON Web Token headers, payloads, and signatures with detailed breakdown and validation.", category: "Security Tools", slug: "jwt-decoder", popularity: 95, icon: "Key", featured: true, trending: true, keywords: ["jwt", "json web token", "decode", "token", "header", "payload"] },
  { id: "s2", name: "JWT Generator", description: "Free online JWT generator for developers. Create JSON Web Tokens with custom claims, headers, and multiple signing algorithms like HMAC and RSA.", category: "Security Tools", slug: "jwt-generator", popularity: 78, icon: "KeyRound" },
  { id: "s3", name: "Hash Generator", description: "Free online hash generator supporting MD5, SHA-1, SHA-256, SHA-384, and SHA-512 algorithms. Generate cryptographic hashes for text and files.", category: "Security Tools", slug: "hash-generator", popularity: 81, icon: "Shield", featured: true, worker: true, aliasSlugs: ["md5-generator", "sha256-generator", "checksum"], keywords: ["hash", "md5", "sha1", "sha256", "sha512", "checksum", "digest"] },
  { id: "s4", name: "TOTP Generator", description: "Free TOTP generator for two-factor authentication setup and testing. Generate time-based one-time passwords compatible with authenticator apps.", category: "Security Tools", slug: "totp-generator", popularity: 72, icon: "Smartphone" },
  { id: "s5", name: "SSL Certificate Decoder", description: "Free online SSL certificate decoder for security analysis. Decode and inspect PEM and X.509 SSL certificates with detailed field information.", category: "Security Tools", slug: "ssl-decoder", popularity: 68, icon: "ShieldCheck" },
  { id: "s6", name: "CSP Generator", description: "Free Content Security Policy header generator with visual builder. Create and test CSP policies to protect your website from XSS and injection attacks.", category: "Security Tools", slug: "csp-generator", popularity: 62, icon: "ShieldAlert" },
  { id: "s7", name: "File Checksum Calculator", description: "Free online file checksum calculator for integrity verification. Calculate MD5, SHA-1, SHA-256, and SHA-512 checksums for any file upload.", category: "Security Tools", slug: "file-checksum", popularity: 66, icon: "FileCheck" },
  { id: "s8", name: "JSON Schema Generator", description: "Free online JSON Schema generator from sample data. Automatically create JSON Schema definitions to validate and document your JSON structures.", category: "Security Tools", slug: "json-schema-generator", popularity: 74, icon: "Files", new: true },

  // ── Crypto Tools (6) ──
  { id: "s9", name: "Bcrypt Generator", description: "Free online bcrypt password hash generator and verifier for developers. Generate bcrypt hashes and verify passwords against existing hash values.", category: "Security Tools", slug: "bcrypt-generator", popularity: 72, icon: "Lock" },
  { id: "s10", name: "ULID Generator", description: "Free ULID generator tool for developers. Create Universally Unique Lexicographically Sortable Identifiers for database keys and distributed systems.", category: "Security Tools", slug: "ulid-generator", popularity: 68, icon: "FingerprintPattern" },
  { id: "s11", name: "HMAC Generator", description: "Free online HMAC signature generator supporting SHA-256, SHA-512, and more algorithms. Create hash-based message authentication codes for APIs.", category: "Security Tools", slug: "hmac-generator", popularity: 70, icon: "Key" },
  { id: "s12", name: "RSA Key Pair Generator", description: "Free online RSA key pair generator for developers. Create secure RSA public and private key pairs for encryption, decryption, and digital signatures.", category: "Security Tools", slug: "rsa-key-generator", popularity: 66, icon: "KeyRound" },
  { id: "s13", name: "Password Strength Analyser", description: "Free online password strength analyser tool. Evaluate password security, entropy level, and estimated crack time with detailed improvement suggestions.", category: "Security Tools", slug: "password-strength", popularity: 74, icon: "Shield" },
  { id: "s14", name: "BIP39 Mnemonic Generator", description: "Free BIP39 mnemonic phrase generator for cryptocurrency wallets. Create secure seed phrases for Bitcoin, Ethereum, and other crypto wallet setup.", category: "Security Tools", slug: "bip39-generator", popularity: 64, icon: "Key" },

  // ── Additional Security Tools (5) ──
  { id: "s15", name: "MAC Address Lookup", description: "Free online MAC address lookup tool. Identify the manufacturer and vendor of any MAC address for network administration and security analysis.", category: "Security Tools", slug: "mac-address-lookup", popularity: 60, icon: "Search" },
  { id: "s16", name: "MAC Address Generator", description: "Free random MAC address generator for network testing and development. Generate valid MAC addresses with custom OUI prefixes for device simulation.", category: "Security Tools", slug: "mac-address-generator", popularity: 56, icon: "Shuffle" },
  { id: "s17", name: "Phone Number Parser", description: "Free online international phone number parser and formatter. Validate and format phone numbers from any country with standardized output formats.", category: "Security Tools", slug: "phone-number-parser", popularity: 62, icon: "Smartphone" },
  { id: "s18", name: "IBAN Validator", description: "Free online IBAN validator and parser for international banking. Validate and analyze International Bank Account Numbers with country-specific rules.", category: "Security Tools", slug: "iban-validator", popularity: 58, icon: "FileCheck" },
  { id: "s19", name: "Encrypt / Decrypt", description: "Free online encryption and decryption tool supporting AES, TripleDES, Rabbit, and RC4 algorithms. Secure your text data with multiple cipher options.", category: "Security Tools", slug: "encrypt-decrypt", popularity: 70, icon: "Lock" },

  // ── Image Tools (9) ──
  { id: "i1", name: "Image Compressor", description: "Free online image compressor with quality control for JPEG, PNG, and WebP formats. Reduce image file sizes without losing visible quality for web.", category: "Image Tools", slug: "image-compressor", popularity: 87, icon: "ImageMinus", featured: true, wasm: false, keywords: ["image", "compress", "resize", "optimize", "jpeg", "png", "webp"] },
  { id: "i2", name: "Image Resizer", description: "Free online image resizer, compressor, and converter with batch processing support. Resize multiple images to any dimensions with quality retention.", category: "Image Tools", slug: "image-resizer", popularity: 83, icon: "Crop", featured: true, wasm: false, keywords: ["image", "resize", "crop", "scale", "dimensions"] },
  { id: "i3", name: "Favicon Generator", description: "Free favicon generator tool for websites. Create favicons and app icons from images or text for all platforms including Apple and Android devices.", category: "Image Tools", slug: "favicon-generator", popularity: 70, icon: "Square" },
  { id: "i4", name: "SVG Optimizer", description: "Free online SVG optimizer and minifier powered by SVGO. Reduce SVG file sizes by removing unnecessary metadata while preserving visual quality.", category: "Image Tools", slug: "svg-optimizer", popularity: 68, icon: "Image" },
  { id: "i5", name: "Placeholder Image Generator", description: "Free placeholder image generator with custom dimensions and colors. Create temporary placeholder images for web design and prototyping layouts.", category: "Image Tools", slug: "placeholder-image", popularity: 64, icon: "ImagePlus" },
  { id: "i6", name: "SVG to CSS Converter", description: "Free SVG to CSS converter tool for web developers. Convert SVG code to optimized CSS background-image data URIs for inline embedding.", category: "Image Tools", slug: "svg-to-css", popularity: 66, icon: "FileCode" },
  { id: "i7", name: "EXIF Reader", description: "Free online EXIF reader and metadata viewer for images. Extract and view camera settings, GPS coordinates, and other embedded image metadata.", category: "Image Tools", slug: "exif-reader", popularity: 72, icon: "Info" },
  { id: "i8", name: "EXIF Transfer", description: "Free online EXIF metadata transfer tool. Copy and transfer EXIF data from one image to another while preserving original image quality intact.", category: "Image Tools", slug: "exif-transfer", popularity: 52, icon: "ArrowLeftRight" },
  { id: "i9", name: "Color Eyedropper", description: "Free online color eyedropper and picker tool for designers. Pick and extract colors from anywhere on your screen with HEX, RGB, and HSL values.", category: "Image Tools", slug: "color-eyedropper", popularity: 60, icon: "Droplets" },

  // ── Utilities (31) ──
  { id: "u1", name: "Regex Tester", description: "Free online regex tester and debugger with real-time matching, capture groups, and extended flag support. Test and debug regular expressions easily.", category: "Utilities", slug: "regex-tester", popularity: 77, icon: "SearchCode", featured: true, worker: true, keywords: ["regex", "regular expression", "pattern", "match", "test"] },
  { id: "u2", name: "Text Diff Checker", description: "Free online text diff checker and comparison tool. Compare two texts side-by-side or in unified view with highlighted additions and deletions.", category: "Utilities", slug: "diff-checker", popularity: 64, icon: "GitCompare" },
  { id: "u3", name: "Word Counter", description: "Free online word counter and text analyzer tool. Count words, characters, sentences, and analyze readability with Flesch reading ease scores.", category: "Utilities", slug: "word-counter", popularity: 80, icon: "Hash", featured: true },
  { id: "u4", name: "Text Sorter & Deduplicator", description: "Free online text sorter and deduplicator tool. Sort lines alphabetically, remove duplicates, filter empty lines, and randomize text order.", category: "Utilities", slug: "text-sorter", popularity: 62, icon: "ArrowUpDown", worker: true, keywords: ["text", "sort", "deduplicate", "remove duplicates", "alphabetical"] },
  { id: "u5", name: "HTTP Header Parser", description: "Free online HTTP header parser and analyzer for developers. Inspect and debug HTTP request and response headers with detailed field breakdown.", category: "Utilities", slug: "http-header-parser", popularity: 68, icon: "Globe" },
  { id: "u6", name: "URL Parser", description: "Free online URL parser and analyzer tool for developers. Break down URLs into protocol, host, path, query parameters, and hash components.", category: "Utilities", slug: "url-parser", popularity: 70, icon: "Link2" },
  { id: "u7", name: "User Agent Parser", description: "Free online user agent string parser and analyzer. Extract browser, OS, and device information from any User-Agent header string instantly.", category: "Utilities", slug: "user-agent-parser", popularity: 66, icon: "Monitor" },
  { id: "u8", name: "IP Address Calculator", description: "Free online IP address calculator and subnet tool. Calculate subnet masks, CIDR notation, host ranges, and network addresses for IPv4.", category: "Utilities", slug: "ip-calculator", popularity: 74, icon: "Network", featured: true },
  { id: "u9", name: "JSON Path Finder", description: "Free online JSON path finder and extractor tool. Find and extract specific values from complex JSON data using JSONPath expressions quickly.", category: "Utilities", slug: "json-path-finder", popularity: 72, icon: "Search" },
  { id: "u10", name: "Markdown Preview", description: "Free online Markdown preview editor with live syntax highlighting. Write and preview Markdown documents in real-time with formatted output.", category: "Utilities", slug: "markdown-preview", popularity: 76, icon: "FileText" },
  { id: "u11", name: "Slug Generator", description: "Free URL slug generator with transliteration support for web developers. Convert any text into URL-safe slug strings for clean web addresses.", category: "Utilities", slug: "slug-generator", popularity: 60, icon: "Link" },
  { id: "u12", name: "String Length Calculator", description: "Free online string length calculator for developers. Measure string length in bytes, characters, and Unicode code points with detailed breakdown.", category: "Utilities", slug: "string-length", popularity: 58, icon: "Ruler" },
  { id: "u13", name: "DNS Lookup", description: "Free online DNS lookup tool for network administrators. Perform A, AAAA, MX, NS, TXT, and CNAME record lookups for any domain name.", category: "Utilities", slug: "dns-lookup", popularity: 62, icon: "Globe" },
  { id: "u14", name: "IP Address Lookup", description: "Free online IP address lookup and geolocation tool. Find location, ISP, ASN, and network details for any IP address worldwide instantly.", category: "Utilities", slug: "ip-lookup", popularity: 65, icon: "Network" },
  { id: "u15", name: "Basic Auth Generator", description: "Free HTTP Basic Authentication header generator tool for developers. Create Authorization headers for testing APIs and protected endpoints.", category: "Utilities", slug: "basic-auth-generator", popularity: 62, icon: "Key" },
  { id: "u16", name: "MIME Types Lookup", description: "Free online MIME types lookup tool for web developers. Find MIME types by file extension or discover file extensions for any MIME type.", category: "Utilities", slug: "mime-types", popularity: 60, icon: "FileCode" },
  { id: "u17", name: "Keycode Info", description: "Free online keyboard keycode information reference tool. Display key codes, which, and location values for keyboard key press events in browsers.", category: "Utilities", slug: "keycode-info", popularity: 55, icon: "Hash" },
  { id: "u18", name: "Slug Generator", description: "Free online string to URL slug converter. Transform any text into clean, URL-friendly slugs for web development and content management.", category: "Utilities", slug: "slugify-string", popularity: 64, icon: "Link" },
  { id: "u19", name: "Safelink Decoder", description: "Free online safelink and URL shortener decoder tool. Reveal and decode redirect URLs from URL shorteners and safelink wrapper services.", category: "Utilities", slug: "safelink-decoder", popularity: 56, icon: "Link2" },
  { id: "u20", name: "Device Information", description: "Free online device and browser information tool. Display detailed hardware, software, screen, and network information for your current device.", category: "Utilities", slug: "device-information", popularity: 58, icon: "Monitor" },
  { id: "u21", name: "Email Normalizer", description: "Free online email address normalizer tool. Clean and normalize email addresses by removing aliases, plus addressing, and formatting inconsistencies.", category: "Utilities", slug: "email-normalizer", popularity: 55, icon: "FileText" },
  { id: "u22", name: "Text Diff Visualizer", description: "Free online text diff visualizer for comparing documents. View side-by-side or inline text comparisons with clearly highlighted changes and edits.", category: "Utilities", slug: "text-diff-visual", popularity: 65, icon: "GitCompare" },
  { id: "u23", name: "String Obfuscator", description: "Free online string obfuscation tool for developers. Encode text using hex, binary, ROT13, Base64, and other encoding methods for protection.", category: "Utilities", slug: "string-obfuscator", popularity: 60, icon: "Quote" },
  { id: "u24", name: "Math Evaluator", description: "Free online math expression evaluator and calculator. Evaluate complex mathematical expressions with support for functions and variables.", category: "Utilities", slug: "math-evaluator", popularity: 68, icon: "Hash" },
  { id: "u25", name: "Chronometer", description: "Free online stopwatch and chronometer with lap tracking. Measure precise time intervals with split timing for sports, cooking, and testing.", category: "Utilities", slug: "chronometer", popularity: 58, icon: "Clock" },
  { id: "u26", name: "Percentage Calculator", description: "Free online percentage calculator for quick math calculations. Compute percentages, percentage changes, increases, decreases, and differences.", category: "Utilities", slug: "percentage-calculator", popularity: 70, icon: "Hash" },
  { id: "u27", name: "Emoji Picker", description: "Free online emoji picker and browser tool with search functionality. Find and copy the perfect emoji from categorized libraries with ease.", category: "Utilities", slug: "emoji-picker", popularity: 72, icon: "Search" },
  { id: "u28", name: "IPv4 Subnet Calculator", description: "Free online IPv4 subnet calculator for network planning. Calculate subnets, ranges, broadcast addresses, and host counts from CIDR notation.", category: "Utilities", slug: "ipv4-subnet-calculator", popularity: 64, icon: "Network" },
  { id: "u29", name: "IPv4 Address Converter", description: "Free online IPv4 address format converter for network engineers. Convert between decimal, hexadecimal, binary, and dotted notation formats.", category: "Utilities", slug: "ipv4-address-converter", popularity: 62, icon: "Binary" },
  { id: "u30", name: "IPv4 Range Expander", description: "Free online IPv4 CIDR range expander tool. Expand CIDR notation ranges into lists of individual IP addresses for network configuration.", category: "Utilities", slug: "ipv4-range-expander", popularity: 58, icon: "ArrowUpDown" },
  { id: "u31", name: "IPv6 ULA Generator", description: "Free online IPv6 Unique Local Address generator for network administrators. Create random ULA addresses for private internal network configurations.", category: "Utilities", slug: "ipv6-ula-generator", popularity: 55, icon: "Globe" },

  // ── Additional Utilities (5) ──
  { id: "u32", name: "Chmod Calculator", description: "Free online chmod calculator with visual checkbox grid for Unix file permissions. Calculate read, write, and execute permission modes easily.", category: "Utilities", slug: "chmod-calculator", popularity: 60, icon: "Calculator" },
  { id: "u33", name: "ETA Calculator", description: "Free online ETA calculator for estimated travel time. Calculate arrival time based on distance, speed, and current time for trip planning.", category: "Utilities", slug: "eta-calculator", popularity: 56, icon: "Clock" },
  { id: "u34", name: "HTTP Status Codes", description: "Free HTTP status code reference guide for web developers. Quick lookup for all HTTP response codes with descriptions and common use cases.", category: "Utilities", slug: "http-status-codes", popularity: 68, icon: "Globe" },
  { id: "u35", name: "Git Cheatsheet", description: "Free interactive Git cheatsheet and command reference for developers. Quickly find and copy Git commands for common version control operations.", category: "Utilities", slug: "git-cheatsheet", popularity: 72, icon: "GitBranch" },
  { id: "u36", name: "Regex Cheatsheet", description: "Free interactive regular expression cheatsheet with examples. Quick reference for regex patterns, syntax, and common matching expressions.", category: "Utilities", slug: "regex-memo", popularity: 64, icon: "SearchCode" },
];

export const TOOL_COUNT = allTools.length;

export const categories: Category[] = categoryMetas.map((c) => ({
  ...c,
  toolCount: allTools.filter((t) => t.category === c.name).length,
}));

export const featuredTools: Tool[] = allTools.filter((t) => t.featured);

export const benefits = [
  { title: "Free Forever", description: "All tools are completely free. No hidden charges, no credit card needed.", icon: "Gift" },
  { title: "Browser-Based", description: "Everything runs in your browser. No downloads or installations required.", icon: "Globe" },
  { title: "No Login", description: "Start using tools immediately. No account creation, no passwords to remember.", icon: "LogOut" },
  { title: "Privacy-First", description: "Your data stays on your device. We never store or share your information.", icon: "Shield" },
  { title: "Lightning Fast", description: "Optimized for speed. Tools load instantly and respond in real-time.", icon: "Zap" },
  { title: "Mobile Friendly", description: "Fully responsive design that works on any device, from phone to desktop.", icon: "Smartphone" },
  { title: "Keyboard Shortcuts", description: "Power-user shortcuts for efficient workflows and quick tool access.", icon: "Keyboard" },
  { title: "Secure", description: "HTTPS everywhere. Your data is encrypted in transit and never persisted.", icon: "Lock" },
];

export const learningTopics = [
  { title: "Getting Started with JSON", description: "Learn the fundamentals of JSON syntax, structure, and common use cases in modern web development.", slug: "getting-started-json", readTime: "5 min" },
  { title: "Understanding JWT Tokens", description: "A comprehensive guide to JSON Web Tokens, how they work, and best practices for implementation.", slug: "understanding-jwt", readTime: "8 min" },
  { title: "Image Optimization Guide", description: "Best practices for optimizing images for the web without sacrificing quality.", slug: "image-optimization-guide", readTime: "6 min" },
  { title: "Password Security Best Practices", description: "How to create and manage secure passwords, plus common pitfalls to avoid.", slug: "password-security", readTime: "4 min" },
  { title: "Understanding Base64 Encoding", description: "What Base64 is, how it works, and when to use it in web development.", slug: "understanding-base64", readTime: "6 min" },
  { title: "CSS Minification Guide", description: "How to minify CSS for production and why it matters for performance.", slug: "css-minification-guide", readTime: "5 min" },
  { title: "Regex Fundamentals", description: "Learn regular expressions from basics to advanced patterns with practical examples.", slug: "regex-fundamentals", readTime: "10 min" },
  { title: "Unix Timestamps Explained", description: "Everything you need to know about Unix timestamps, timezones, and date handling.", slug: "unix-timestamps-explained", readTime: "7 min" },
  { title: "HTML Encoding & Special Characters", description: "A guide to HTML entities, special characters, and why encoding matters for security.", slug: "html-encoding-guide", readTime: "5 min" },
  { title: "Data Serialization Formats", description: "Compare JSON, YAML, TOML, and XML to choose the right format for your project.", slug: "data-serialization-formats", readTime: "8 min" },
];

export const faqItems = [
  { question: "Are the tools really free?", answer: "Yes, all tools on DevStackIO are completely free. We believe developer tools should be accessible to everyone." },
  { question: "Do I need to create an account?", answer: "No. Every tool works without any account or login. Just open and use." },
  { question: "Is my data secure?", answer: "All processing happens in your browser. Your data never leaves your device, and we never store or share your information." },
  { question: "Can I use these tools offline?", answer: "Many tools work offline after the first load. We're working on expanding offline support." },
  { question: "How do you sustain the platform?", answer: "We're building a premium API for enterprise users. All web tools remain free forever." },
  { question: "How many tools are available?", answer: `We currently offer ${TOOL_COUNT} free tools across ${categories.length} categories, with new tools added regularly.` },
  { question: "Do you support mobile devices?", answer: "Yes, all tools are fully responsive and work on smartphones, tablets, and desktops." },
  { question: "Can I request a new tool?", answer: "Absolutely! Use the Suggest a Tool page to let us know what you need." },
];
