import {
  create,
  typedDependencies,
  parseDependencies,
  evaluateDependencies,
  addDependencies,
  subtractDependencies,
  multiplyDependencies,
  divideDependencies,
  powDependencies,
  modDependencies,
  unaryMinusDependencies,
  unaryPlusDependencies,
  sqrtDependencies,
  absDependencies,
  ceilDependencies,
  floorDependencies,
  sinDependencies,
  cosDependencies,
  tanDependencies,
  logDependencies,
  log10Dependencies,
  log2Dependencies,
  piDependencies,
  eDependencies,
  factorialDependencies,
  roundDependencies,
  expDependencies,
} from "mathjs";

const math = create({
  ...typedDependencies,
  ...parseDependencies,
  ...evaluateDependencies,
  ...addDependencies,
  ...subtractDependencies,
  ...multiplyDependencies,
  ...divideDependencies,
  ...powDependencies,
  ...modDependencies,
  ...unaryMinusDependencies,
  ...unaryPlusDependencies,
  ...sqrtDependencies,
  ...absDependencies,
  ...ceilDependencies,
  ...floorDependencies,
  ...sinDependencies,
  ...cosDependencies,
  ...tanDependencies,
  ...logDependencies,
  ...log10Dependencies,
  ...log2Dependencies,
  ...piDependencies,
  ...eDependencies,
  ...factorialDependencies,
  ...roundDependencies,
  ...expDependencies,
});

export const limitedEvaluate = math.evaluate.bind(math);
