import { test, expect, type Page, type Route } from "@playwright/test";
import { readFileSync } from "node:fs";

const BASE_URL = "http://localhost:3000";

// Minimal valid WebAssembly module (only the 8-byte header). Compiling this
// exercises the 'wasm-unsafe-eval' CSP directive: when absent, Chrome throws
// a SecurityError on instantiation.
const MINIMAL_WASM_BASE64 = "AGFzbQEAAAA=";

interface RouteCsp {
  scripts: string[];
  styles: string[];
  csp: string;
}

interface CspData {
  defaultCsp: string;
  perRoute: Record<string, RouteCsp>;
}

// Generated by scripts/postbuild-csp.mjs during `npm run build`.
const cspData = JSON.parse(readFileSync("data/csp-hashes.json", "utf-8")) as CspData;

// Must stay in sync with WASM_ROUTES in scripts/postbuild-csp.mjs.
const WASM_ROUTES = [
  "/tools/hash-generator",
  "/tools/md5-generator",
  "/tools/sha256-generator",
  "/tools/checksum",
  "/tools/file-checksum",
  "/toolkits/security-toolkit",
];

// Must stay in sync with EVAL_ROUTES in scripts/postbuild-csp.mjs.
const EVAL_ROUTES = [
  "/tools/benchmark-builder",
];

// The standalone Node server used for local tests does not emit CSP headers
// (Nginx applies them in production), so each test injects the exact
// per-route CSP produced by postbuild-csp.mjs. This verifies the real
// policies the browser will receive, hermetically.
async function applyGeneratedCsp(page: Page, csp: string) {
  await page.route("**/*", async (route: Route) => {
    if (/googlesyndication\.com|doubleclick\.net|gstatic|cloudflareinsights|google-analytics|googletagmanager|adtrafficquality/.test(route.request().url())) {
      await route.abort().catch(() => {});
      return;
    }
    const response = await route.fetch();
    await route.fulfill({
      response,
      headers: {
        ...response.headers(),
        "content-security-policy": csp,
      },
    });
  });
}

async function tryInstantiateWasm(page: Page): Promise<boolean> {
  return page.evaluate(async (b64) => {
    const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
    try {
      const result = await WebAssembly.instantiate(bytes, {});
      return result.instance !== null;
    } catch {
      return false;
    }
  }, MINIMAL_WASM_BASE64);
}

test.describe("WASM CSP scoping", () => {
  test("no generated route CSP grants bare 'unsafe-eval' or 'unsafe-inline'", () => {
    const routes = Object.entries(cspData.perRoute);
    expect(routes.length).toBeGreaterThan(100);
    for (const [route, entry] of routes) {
      const isEvalRoute = EVAL_ROUTES.includes(route);
      // Exact quoted tokens: cannot false-positive on 'wasm-unsafe-eval'.
      expect(entry.csp.includes("'unsafe-eval'"), `${route} grants unsafe-eval`).toBe(isEvalRoute);
      expect(entry.csp.includes("'unsafe-inline'"), `${route} grants unsafe-inline`).toBe(false);
    }
  });

  test("'wasm-unsafe-eval' is granted only to WASM-using routes", () => {
    const granted = Object.entries(cspData.perRoute)
      .filter(([, entry]) => entry.csp.includes("'wasm-unsafe-eval'"))
      .map(([route]) => route)
      .sort();
    expect(granted.sort()).toEqual([...WASM_ROUTES].sort());
  });

  test("'unsafe-eval' is granted only to EVAL-using routes", () => {
    const granted = Object.entries(cspData.perRoute)
      .filter(([, entry]) => entry.csp.includes("'unsafe-eval'"))
      .map(([route]) => route)
      .sort();
    expect(granted.sort()).toEqual([...EVAL_ROUTES].sort());
  });

  test("WebAssembly compiles under the hash-generator route CSP", async ({ page }) => {
    const csp = cspData.perRoute["/tools/hash-generator"].csp;
    expect(csp).toContain("'wasm-unsafe-eval'");
    await applyGeneratedCsp(page, csp);
    await page.goto(`${BASE_URL}/tools/hash-generator`, { waitUntil: "networkidle" });
    expect(await tryInstantiateWasm(page)).toBe(true);
  });

  test("WebAssembly compile is denied under the json-formatter route CSP", async ({ page }) => {
    const csp = cspData.perRoute["/tools/json-formatter"].csp;
    expect(csp).not.toContain("'wasm-unsafe-eval'");
    await applyGeneratedCsp(page, csp);
    await page.goto(`${BASE_URL}/tools/json-formatter`, { waitUntil: "networkidle" });
    expect(await tryInstantiateWasm(page)).toBe(false);
  });

  test("WebAssembly compile is denied on the homepage CSP", async ({ page }) => {
    await applyGeneratedCsp(page, cspData.perRoute["/"].csp);
    await page.goto(`${BASE_URL}/`, { waitUntil: "networkidle" });
    expect(await tryInstantiateWasm(page)).toBe(false);
  });
});
