import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { spawnSync } from "node:child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const OUTPUT_DIR = join(ROOT, "src", "lib", "version", "__generated__");
const OUTPUT_FILE = join(OUTPUT_DIR, "release-data.ts");

function parseEnvFile(path) {
  try {
    const raw = readFileSync(path, "utf-8");
    const out = {};
    for (const line of raw.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq <= 0) continue;
      const key = trimmed.slice(0, eq).trim();
      const value = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, "");
      if (key) out[key] = value;
    }
    return out;
  } catch {
    return {};
  }
}

function loadNextEnv() {
  const nodeEnv = process.env.NODE_ENV || "production";
  const merged = {};
  const files = [".env", `.env.${nodeEnv}`, ".env.local", `.env.${nodeEnv}.local`];
  for (const file of files) {
    Object.assign(merged, parseEnvFile(join(ROOT, file)));
  }
  return merged;
}

function exec(command) {
  try {
    return execSync(command, { encoding: "utf-8", timeout: 5000 }).trim();
  } catch {
    return "";
  }
}

function getGitInfo() {
  const commit = exec("git log -1 --format=%H");
  const branch = exec("git rev-parse --abbrev-ref HEAD");
  const countStr = exec("git rev-list --count HEAD");
  const status = exec("git status --porcelain");
  const count = parseInt(countStr, 10);
  return {
    commit: commit || "0000000000000000000000000000000000000000",
    shortHash: commit ? commit.slice(0, 7) : "0000000",
    branch: branch || "unknown",
    commitCount: !isNaN(count) && count > 0 ? count : 0,
    isDirty: status.length > 0,
  };
}

function getNextVersion() {
  try {
    const nextPkgPath = join(ROOT, "node_modules", "next", "package.json");
    const raw = readFileSync(nextPkgPath, "utf-8");
    return JSON.parse(raw).version || "unknown";
  } catch {
    return "unknown";
  }
}

function getVersion() {
  try {
    const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf-8"));
    return pkg.version || "0.0.0";
  } catch {
    return "0.0.0";
  }
}

function getBuildNumber() {
  const path = join(ROOT, "data", "build-number.json");
  try {
    const raw = readFileSync(path, "utf-8");
    const data = JSON.parse(raw);
    return typeof data.buildNumber === "number" ? data.buildNumber : 0;
  } catch {
    return 0;
  }
}

const version = getVersion();
const buildNumber = getBuildNumber();
const git = getGitInfo();
const now = new Date();

const content = `// This file is auto-generated by scripts/prebuild.mjs
// DO NOT EDIT MANUALLY — changes will be overwritten during build.

export const RELEASE_VERSION = ${JSON.stringify(version)};
export const RELEASE_BUILD_NUMBER = ${buildNumber};
export const RELEASE_GIT_COMMIT = ${JSON.stringify(git.commit)};
export const RELEASE_GIT_SHORT_HASH = ${JSON.stringify(git.shortHash)};
export const RELEASE_GIT_BRANCH = ${JSON.stringify(git.branch)};
export const RELEASE_GIT_COMMIT_COUNT = ${git.commitCount};
export const RELEASE_GIT_IS_DIRTY = ${git.isDirty};
export const RELEASE_BUILD_TIME = ${now.getTime()};
export const RELEASE_BUILD_DATE = ${JSON.stringify(now.toISOString())};
export const RELEASE_NODE_VERSION = ${JSON.stringify(process.version)};
export const RELEASE_NEXT_VERSION = ${JSON.stringify(getNextVersion())};
export const RELEASE_ENVIRONMENT = ${JSON.stringify(process.env.NODE_ENV || "development")};
`;

if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

writeFileSync(OUTPUT_FILE, content, "utf-8");
console.log(`[prebuild] Generated ${OUTPUT_FILE}`);
console.log(`[prebuild] Version: ${version}, Build: ${buildNumber}`);

const GA_ID = process.env.NEXT_PUBLIC_GA_ID || loadNextEnv().NEXT_PUBLIC_GA_ID || "";
const analyticsInitFile = join(ROOT, "public", "analytics-init.js");
const analyticsInitContent = GA_ID
  ? `(function(){window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments);};window.gtag('js',new Date());window.gtag('config','${GA_ID}',{anonymize_ip:true,allow_google_signals:false,allow_ad_personalization_signals:false});})();
`
  : `(function(){window.dataLayer=window.dataLayer||[];})();
`;
writeFileSync(analyticsInitFile, analyticsInitContent, "utf-8");
console.log(
  `[prebuild] Generated ${analyticsInitFile} (GA_ID ${GA_ID ? "set" : "empty"})`
);

console.log("[prebuild] Building WASM modules...");
const wasmRes = spawnSync(process.execPath, [join(__dirname, "build-wasm.mjs")], {
  stdio: "inherit",
});
if (wasmRes.status !== 0) {
  process.exit(wasmRes.status ?? 1);
}
